export const GET_FOOTBALL_COMPETITIONS_BY_YEAR = Symbol( 'GET_FOOTBALL_COMPETITIONS_BY_YEAR' )
export const GET_FOOTBALL_COMPETITIONS_SUCCESS = Symbol( 'GET_FOOTBALL_COMPETITIONS_SUCCESS' )
export const GET_FOOTBALL_COMPETITIONS_FAILURE = Symbol( 'GET_FOOTBALL_COMPETITIONS_FAILURE' )